-- 0010_reference_ranges: named, cited ranges that a reading can be compared against.
--
-- `ReferenceRange` (packages/protocol/src/ars_protocol/health.py) has no `id` field —
-- deliberately, per its docstring, it is a citation, not a record about the user. `id`
-- here is therefore a database-only primary key, generated by the store and never
-- round-tripped back onto the protocol type.
--
-- Keyed by (kind, source): the same source updating its own guidance overwrites its own
-- row (an upsert), but two different sources may both publish a range for the same
-- kind, and both are kept — a finding cites whichever range it was measured against,
-- and only the caller (never this table) decides which citation to prefer.
CREATE TABLE reference_ranges (
    id       TEXT NOT NULL UNIQUE,   -- classification: identifier only, internal — never exposed on ReferenceRange
    kind     TEXT NOT NULL,          -- classification: identifier only (VitalKind enum value)
    low      REAL,                   -- classification: identifier only — a published guideline number, not the user's data
    high     REAL,                   -- classification: identifier only
    source   TEXT NOT NULL,          -- classification: identifier only — required by the protocol type; a range with no citation may not exist
    note     TEXT                    -- classification: identifier only
);

CREATE UNIQUE INDEX idx_reference_ranges_id ON reference_ranges(id);
CREATE UNIQUE INDEX idx_reference_ranges_kind_source ON reference_ranges(kind, source);
