"""A.R.S protocol — the single source of truth for every message crossing a boundary.

Nothing in this package imports from a service. If a type is needed by two components,
it lives here; if only one component uses it, it does not belong here.
"""

from .health import (
    PLAUSIBLE, DeviceKind, RangeFinding, ReadingSource, ReferenceRange,
    VitalKind, VitalReading,
)
from .audio import (
    BYTES_PER_FRAME,
    FRAME_MS,
    SAMPLE_RATE_HZ,
    SAMPLES_PER_FRAME,
    AudioEncoding,
    AudioFormat,
    AudioFrame,
    SpeechBoundary,
    SynthesisChunk,
    SynthesisRequest,
    Transcript,
    TranscriptSegment,
    VadEvent,
    WakeEvent,
)
from .capability import (
    Capability,
    CapabilityGrant,
    ConfirmPolicy,
    GrantRequest,
    GrantSource,
    Risk,
)
from .common import (
    DEFAULT_LANGUAGE,
    SUPPORTED_LANGUAGES,
    Confidence,
    Device,
    GrantId,
    Language,
    Model,
    SessionId,
    TurnId,
    new_id,
    now_ms,
)
from .events import (
    AgentState,
    AudioChunk,
    AudioOut,
    ClientEvent,
    ClientEventAdapter,
    ConsentRequired,
    ConsentResponse,
    ErrorEvent,
    GrantChanged,
    Interrupt,
    ObservationProposed,
    ObservationResponse,
    ReplyDelta,
    ReplyDone,
    ServerEvent,
    ServerEventAdapter,
    Session,
    SessionStarted,
    StartSession,
    StateChanged,
    TextInput,
    ToolCallEvent,
    ToolResultEvent,
    TranscriptEvent,
    Turn,
    VoiceActivity,
    WakeDetected,
)
from .guard import (
    AuditRecord,
    ContentBlock,
    DenyReason,
    GuardDecision,
    GuardQuery,
    Provenance,
    SourceKind,
    TrustLevel,
    Verdict,
    taints,
)
from .memory import (
    BehaviourDomain,
    MemoryKind,
    MemoryRecord,
    Observation,
    ObservationStatus,
    Preference,
    Sensitivity,
)
from .skills import SkillManifest, SkillRuntime
from .tools import ToolCall, ToolParam, ToolResult, ToolSpec, ToolStatus

PROTOCOL_VERSION = "0.1.0"

# Explicit, so the public surface is reviewable in a diff and linters can see it.
__all__ = [
    "VitalReading",
    "VitalKind",
    "ReferenceRange",
    "ReadingSource",
    "RangeFinding",
    "DeviceKind",
    "PLAUSIBLE",
    "BYTES_PER_FRAME",
    "DEFAULT_LANGUAGE",
    "FRAME_MS",
    "PROTOCOL_VERSION",
    "SAMPLES_PER_FRAME",
    "SAMPLE_RATE_HZ",
    "SUPPORTED_LANGUAGES",
    "AgentState",
    "AudioChunk",
    "AudioEncoding",
    "AudioFormat",
    "AudioFrame",
    "AudioOut",
    "AuditRecord",
    "BehaviourDomain",
    "Capability",
    "CapabilityGrant",
    "ClientEvent",
    "ClientEventAdapter",
    "Confidence",
    "ConfirmPolicy",
    "ConsentRequired",
    "ConsentResponse",
    "ContentBlock",
    "DenyReason",
    "Device",
    "ErrorEvent",
    "GrantChanged",
    "GrantId",
    "GrantRequest",
    "GrantSource",
    "GuardDecision",
    "GuardQuery",
    "Interrupt",
    "Language",
    "MemoryKind",
    "MemoryRecord",
    "Model",
    "Observation",
    "ObservationProposed",
    "ObservationResponse",
    "ObservationStatus",
    "Preference",
    "Provenance",
    "ReplyDelta",
    "ReplyDone",
    "Risk",
    "Sensitivity",
    "ServerEvent",
    "ServerEventAdapter",
    "Session",
    "SessionId",
    "SessionStarted",
    "SkillManifest",
    "SkillRuntime",
    "SourceKind",
    "SpeechBoundary",
    "StartSession",
    "StateChanged",
    "SynthesisChunk",
    "SynthesisRequest",
    "TextInput",
    "ToolCall",
    "ToolCallEvent",
    "ToolParam",
    "ToolResult",
    "ToolResultEvent",
    "ToolSpec",
    "ToolStatus",
    "Transcript",
    "TranscriptEvent",
    "TranscriptSegment",
    "TrustLevel",
    "Turn",
    "TurnId",
    "VadEvent",
    "Verdict",
    "VoiceActivity",
    "WakeDetected",
    "WakeEvent",
    "new_id",
    "now_ms",
    "taints",
]
